### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by MingzhiYe16** [USCbiostats/PathwayAnalysis#3]
new issue

**Comment by MingzhiYe16** [comment]
Hello Paul, the code didn’t change and still has for (i in IthNode:IthNode)
[image: image.png]

**Comment by pmarjora** [comment]
I’m just working on that now :-)
It’s actually ok as written because the function calculates the value of LISA for just one node.
The loop is there because I wrote this function by borrowing code I had written for Morans-I, in which you do need to go through all nodes. So, for now, I just changed the loop to only consider 1 node. It would make sense to remove the loop eventually, since it isn’t doing anything.

Cheers, Paul
